const make=(name,element,opts={})=>({name,element,normalSide:opts.normalSide||(element==='資産'||element==='費用'?'借方':element==='その他'?'—':'貸方'),statement:opts.statement||(element==='収益'||element==='費用'?'P/L':element==='その他'?'整理用':'B/S'),carry:opts.carry!==undefined?opts.carry:!(element==='収益'||element==='費用'||element==='その他'),role:opts.role||'',desc:opts.desc||'',pair:opts.pair||'',difficulty:opts.difficulty||1,aliases:opts.aliases||[]});
const BOKI_ACCOUNTS=[
make('現金','資産'),make('当座預金','資産'),make('普通預金','資産'),make('定期預金','資産'),make('受取手形','資産'),make('売掛金','資産',{pair:'売上・貸倒引当金'}),make('電子記録債権','資産'),make('繰越商品','資産',{pair:'仕入'}),make('貯蔵品','資産'),make('前払金','資産'),make('仮払金','資産'),make('立替金','資産'),make('未収入金','資産'),make('前払費用','資産'),make('前払保険料','資産',{pair:'保険料'}),make('未収収益','資産'),make('未収利息','資産'),make('未収家賃','資産'),make('仮払消費税','資産'),make('建物','資産'),make('備品','資産'),make('車両運搬具','資産'),make('土地','資産'),
make('貸倒引当金','資産',{normalSide:'貸方',role:'資産の控除評価勘定',desc:'売掛金などの回収不能見込額を、対象資産から控除して表示するための勘定。負債ではありません。',pair:'貸倒引当金繰入'}),make('建物減価償却累計額','資産',{normalSide:'貸方',role:'資産の控除評価勘定',desc:'建物について過年度を含む減価償却累計額を示し、建物の取得原価から控除して表示します。',pair:'減価償却費'}),make('備品減価償却累計額','資産',{normalSide:'貸方',role:'資産の控除評価勘定',desc:'備品について過年度を含む減価償却累計額を示し、備品の取得原価から控除して表示します。',pair:'減価償却費'}),
make('支払手形','負債'),make('買掛金','負債'),make('電子記録債務','負債'),make('借入金','負債'),make('未払金','負債'),make('前受金','負債'),make('仮受金','負債'),make('預り金','負債'),make('所得税預り金','負債',{pair:'給料'}),make('社会保険料預り金','負債',{pair:'給料・法定福利費'}),make('未払費用','負債'),make('未払利息','負債',{pair:'支払利息'}),make('前受収益','負債'),make('前受家賃','負債',{pair:'受取家賃'}),make('未払法人税等','負債'),make('未払消費税','負債'),make('仮受消費税','負債'),
make('資本金','純資産'),make('繰越利益剰余金','純資産',{pair:'損益'}),
make('売上','収益'),make('受取利息','収益'),make('受取家賃','収益'),make('雑益','収益'),make('固定資産売却益','収益'),make('償却債権取立益','収益'),
make('仕入','費用'),make('給料','費用'),make('法定福利費','費用'),make('水道光熱費','費用'),make('通信費','費用'),make('旅費交通費','費用'),make('広告宣伝費','費用'),make('支払家賃','費用'),make('支払利息','費用'),make('保険料','費用',{pair:'前払保険料'}),make('租税公課','費用'),make('消耗品費','費用'),make('減価償却費','費用',{pair:'減価償却累計額'}),make('貸倒引当金繰入','費用',{pair:'貸倒引当金'}),make('貸倒損失','費用'),make('雑損','費用'),make('固定資産売却損','費用'),make('法人税等','費用'),make('支払手数料','費用'),
make('現金過不足','その他',{desc:'現金実査額と帳簿残高の差額について、原因が判明するまで一時的に使用する整理勘定。',difficulty:2}),make('損益','その他',{desc:'決算で収益・費用を集め、当期純損益を求めるための決算用勘定。',difficulty:2})
];
const aliases=[];BOKI_ACCOUNTS.forEach(x=>{aliases.push(x);(x.aliases||[]).forEach(a=>aliases.push({...x,name:a,canonical:x.name}))});const BOKI_ACCOUNT_TERMS=aliases;function findBokiAccount(n){return BOKI_ACCOUNT_TERMS.find(x=>x.name===n)||BOKI_ACCOUNTS.find(x=>x.name===n)}
