(function(){
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='daily.html')return;
const mode=()=>new URLSearchParams(location.search).get('mode')||'smart';
let patchedList=false,patchedRecord=false;
function scoreCandidate(c){try{const q=window.BOKI_MASTERY?.get?.(c.source,c.coverageId,{topic:c.topic,skill:'2026範囲補強'});return window.BOKI_MASTERY?.priority?.(q,mode())??-999}catch(e){return-999}}
function shape(c){return{source:c.source,topic:`公式補強・${c.topic}`,q:c.q,answer:c.answer,choices:[...c.choices],display:typeof shuffle==='function'?shuffle([...c.choices]):[...c.choices],exp:c.exp,id:c.coverageId,coverageId:c.coverageId,coverageTopic:c.topic}}
function updateIntro(){try{const counts={q1:0,q2:0,q3:0};list.forEach(x=>{if(counts[x.source]!=null)counts[x.source]++});const mix=document.getElementById('mix');if(mix)mix.innerHTML=Object.entries(counts).filter(([,n])=>n).map(([k,n])=>`<span>${areaLabel[k]} ${n}問</span>`).join('');const r=document.getElementById('reasons');if(r&&!r.querySelector('[data-cov-reason]'))r.insertAdjacentHTML('beforeend','<span data-cov-reason>公式範囲補強も自動選定</span>');const startBtn=document.getElementById('start');if(startBtn&&list.length){startBtn.disabled=false;startBtn.textContent=`▶ ${list.length===10?'この10問':`対象${list.length}問`}を始める`}}catch(e){}}
function patchList(){if(patchedList||typeof list==='undefined'||!Array.isArray(list)||!window.BOKI_COVERAGE_DAILY_POOL||!window.BOKI_MASTERY)return false;const ranked=window.BOKI_COVERAGE_DAILY_POOL.map(c=>({c,p:scoreCandidate(c)})).filter(x=>x.p>-900).sort((a,b)=>b.p-a.p);if(!ranked.length){patchedList=true;return true}const m=mode(),strict=['due','wrong','unlearned'].includes(m),limit=strict?Math.min(4,10):2;let used=0;const usedIdx=new Set();for(const {c} of ranked){if(used>=limit)break;const item=shape(c);if(list.some(x=>x.coverageId===item.coverageId))continue;if(strict&&list.length<10){list.push(item);used++;continue}let at=-1;for(let i=list.length-1;i>=0;i--){if(!usedIdx.has(i)&&list[i].source===item.source&&!list[i].coverageId){at=i;break}}if(at<0&&!strict){for(let i=list.length-1;i>=0;i--){if(!usedIdx.has(i)&&!list[i].coverageId){at=i;break}}}if(at>=0){list[at]=item;usedIdx.add(at);used++}}
 if(list.length>10)list=list.slice(0,10);patchedList=true;updateIntro();return true}
function patchRecord(){if(patchedRecord||typeof record!=='function'||!window.BOKI_MASTERY)return false;const orig=record;const w=function(value,unknown=false){let x=null,ok=false;try{x=list[idx];ok=!unknown&&value===x.answer}catch(e){}const r=orig.apply(this,arguments);if(x?.coverageId){try{window.BOKI_MASTERY.record(x.source,x.coverageId,ok,0,!!unknown,{topic:x.coverageTopic||x.topic,skill:'2026範囲補強'})}catch(e){}}return r};w.__coverageDaily=true;window.record=w;patchedRecord=true;return true}
function boot(n=0){const a=patchList(),b=patchRecord();if((!a||!b)&&n<40)return setTimeout(()=>boot(n+1),120);setTimeout(()=>{if(typeof list!=='undefined'&&!patchedList){patchList()}updateIntro()},700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>boot(),500),{once:true});else setTimeout(()=>boot(),500);
})();