(function(){
'use strict';
if(window.BOKI_MASTERY?.version>=1)return;
const STORE='boki3_mastery_v1';
const SETTINGS='boki3_unified_settings';
const INTERVALS=[1,3,7,14,30,60,90];
const MODULE_STORES={q1:'boki3_q1_trainer_v1',q2:'boki3trainer_v2',q3:'boki3_q3_trainer_v1'};
const moduleNames={q1:'第1問',q2:'第2問',q3:'第3問',daily:'横断10問'};
const safe=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch(e){return f}};
const now=()=>Date.now();
const dayStart=t=>{const d=new Date(t||Date.now());d.setHours(0,0,0,0);return d.getTime()};
const addDays=(t,n)=>{const d=new Date(t);d.setDate(d.getDate()+n);return d.getTime()};
const hash=s=>{let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)};
const normalizeNumbers=s=>String(s||'').replace(/[¥￥]?\s*\d[\d,]*(?:\.\d+)?/g,'#').replace(/\s+/g,' ').trim();
function readSettings(){return Object.assign({masteryTarget:5,masteryAccuracy:80,masteryStreak:3,wrongThreshold:2,reviewStyle:'standard'},window.BOKI_SETTINGS||safe(SETTINGS,{}))}
let db=safe(STORE,{version:1,questions:{},modules:{},updated:0});db.questions||={};db.modules||={};
function save(){db.updated=now();localStorage.setItem(STORE,JSON.stringify(db))}
function key(module,id){return `${module}::${String(id)}`}
function blank(module,id,meta={}){return{module,id:String(id),topic:meta.topic||'',skill:meta.skill||'',seen:0,correct:0,wrong:0,dont:0,streak:0,maxStreak:0,totalTime:0,lastSec:0,last:0,nextReview:0,intervalDays:0,lastResult:'',masteredAt:0}}
function get(module,id,meta={}){const k=key(module,id);if(!db.questions[k])db.questions[k]=blank(module,id,meta);const q=db.questions[k];if(meta.topic&&!q.topic)q.topic=meta.topic;if(meta.skill&&!q.skill)q.skill=meta.skill;return q}
function criteria(q){const s=readSettings(),acc=q.seen?q.correct/q.seen*100:0;return q.correct>=Number(s.masteryTarget||5)&&q.streak>=Number(s.masteryStreak||3)&&acc>=Number(s.masteryAccuracy||80)}
function isMastered(q){return !!q&&criteria(q)}
function level(q){if(!q||!q.seen)return{n:0,label:'未学習',pct:0,cls:'new'};const acc=q.correct/q.seen*100;if(isMastered(q))return{n:4,label:'習熟',pct:100,cls:'mastered'};let n=1;if(q.correct>=2&&acc>=60)n=2;if(q.streak>=2&&acc>=75)n=3;return{n,label:['未学習','学習中','定着中','あと一歩'][n],pct:[0,25,55,80][n],cls:['new','learning','settling','almost'][n]}}
function remaining(q){const s=readSettings();return Math.max(0,Number(s.masteryTarget||5)-(q?.correct||0))}
function record(module,id,ok,sec=0,dont=false,meta={}){if(!module||id==null)return null;const q=get(module,id,meta);const wasMastered=isMastered(q);q.seen++;q.totalTime+=Number(sec||0);q.lastSec=Number(sec||0);q.last=now();q.lastResult=ok?'correct':dont?'dont':'wrong';if(ok){q.correct++;q.streak=(q.streak||0)+1;q.maxStreak=Math.max(q.maxStreak||0,q.streak);let idx=Math.min(INTERVALS.length-1,Math.max(0,q.streak-1));if(sec>30)idx=Math.max(0,idx-1);let interval=INTERVALS[idx];if(wasMastered&&q.intervalDays>=30)interval=q.intervalDays>=60?90:60;q.intervalDays=interval;q.nextReview=addDays(dayStart(q.last),interval)}else{q.wrong++;if(dont)q.dont++;q.streak=0;q.intervalDays=0;q.nextReview=q.last}
if(!wasMastered&&isMastered(q))q.masteredAt=q.last;if(wasMastered&&!isMastered(q))q.masteredAt=0;save();return q}
function due(q,t=now()){return !!q&&q.seen>0&&Number(q.nextReview||0)<=t}
function statusText(q){const l=level(q),acc=q?.seen?Math.round(q.correct/q.seen*100):0;return{...l,acc,remaining:remaining(q),due:due(q),next:q?.nextReview?new Date(q.nextReview):null}}
function priority(q,mode='smart'){const s=readSettings();if(!q)return mode==='unlearned'?100:mode==='smart'?80:-999;if(mode==='unlearned')return q.seen===0?100:-999;if(mode==='wrong')return q.wrong>=Number(s.wrongThreshold||2)?100+q.wrong*5:-999;if(mode==='due')return due(q)?100+Math.min(40,(now()-Number(q.nextReview||now()))/86400000):-999;if(mode==='low')return isMastered(q)?-999:70+(4-level(q).n)*10+(q.wrong||0)*4;
if(isMastered(q)&&!due(q))return-999;let p=0;if(!q.seen)p+=75;if(due(q))p+=50;else if(q.nextReview)p+=Math.max(0,20-(q.nextReview-now())/86400000);p+=(q.wrong||0)*7+(q.dont||0)*9;p+=(4-level(q).n)*7;p+=Math.max(0,30-(q.streak||0)*4);return p}
function moduleSummary(module){const arr=Object.values(db.questions).filter(q=>q.module===module&&q.seen>0);const mastered=arr.filter(isMastered).length,dueN=arr.filter(q=>due(q)).length,weak=arr.filter(q=>!isMastered(q)&&(q.wrong||0)>0).length;return{tracked:arr.length,mastered,due:dueN,weak,pct:arr.length?Math.round(mastered/arr.length*100):0}}
function migrate(){for(const [module,store] of Object.entries(MODULE_STORES)){const d=safe(store,{});for(const [id,z] of Object.entries(d.byQ||{})){let sid=id;if(module==='q1'&&/^DC:/.test(id))sid=id.replace(/:\d+$/,'');if(module==='q1'&&/^(J4|JD):/.test(id)){const parts=id.split(':');const body=parts.slice(2).join(':');sid=`${parts[0]}:${hash(normalizeNumbers(body))}`}
const q=get(module,sid);const seen=Number(z.seen||0);if(seen>q.seen){q.seen=seen;q.correct=Number(z.correct||0);q.wrong=Number(z.wrong||Math.max(0,seen-q.correct));q.dont=Number(z.dont||0);q.last=Number(z.last||0);q.totalTime=Number(z.time||0);q.streak=(q.wrong===0&&q.correct>=3)?Math.min(q.correct,3):0;q.maxStreak=Math.max(q.maxStreak||0,q.streak);if(q.last){const idx=Math.min(INTERVALS.length-1,Math.max(0,q.streak-1));q.intervalDays=INTERVALS[idx]||1;q.nextReview=addDays(dayStart(q.last),q.intervalDays)}else q.nextReview=0}}
}
save()}
function q1Stable(id){id=String(id||'');if(/^DC:/.test(id))return id.replace(/:\d+$/,'');if(/^(J4|JD):/.test(id)){const p=id.split(':');return `${p[0]}:${hash(normalizeNumbers(p.slice(2).join(':')))}`}return id}
function dailyId(x){return `D:${x?.source||'daily'}:${hash(normalizeNumbers(x?.q||''))}`}
function currentContext(){try{
 const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
 if(page==='q1.html'&&typeof session!=='undefined'&&session?.list?.length){const z=session.list[session.index];if(!z)return null;if(session.mode==='phrase')return{module:'q1',id:`PH:${z.id}`,topic:z.group||'言い回し'};if(session.mode==='classify')return{module:'q1',id:`ACC:${z.name}`,topic:'5要素'};if(session.mode==='dc')return{module:'q1',id:`DC:${z.x?.name}:${z.inc?'up':'down'}`,topic:'借方・貸方'};if(session.mode==='j4')return{module:'q1',id:`J4:${hash(normalizeNumbers(z.body))}`,topic:'4択仕訳'};if(session.mode==='drop')return{module:'q1',id:`JD:${hash(normalizeNumbers(z.body))}`,topic:'仕訳組立'};return{module:'q1',id:`Q1:${hash(normalizeNumbers(document.querySelector('#quizCard')?.innerText||''))}`,topic:session.mode||''}}
 if(page==='q2.html'&&typeof session!=='undefined'&&session?.list?.length){const z=session.list[session.index];return z?{module:'q2',id:z.id||`Q2:${hash(normalizeNumbers(z.title||z.transaction||''))}`,topic:z.category||''}:null}
 if(page==='q3.html'){if(typeof currentItem==='function'){const z=currentItem();if(z)return{module:'q3',id:z.id||`Q3:${hash(normalizeNumbers(z.title||z.transaction||''))}`,topic:z.category||z.skill||''}}}
 if(page==='daily.html'&&typeof list!=='undefined'&&typeof idx!=='undefined'&&list?.[idx]){const z=list[idx];return{module:z.source||'daily',id:dailyId(z),topic:z.topic||''}}
 }catch(e){}return null}
function statsHtml(ctx){if(!ctx)return'';const q=get(ctx.module,ctx.id,{topic:ctx.topic}),s=statusText(q);const next=s.next?`${s.due?'復習時期です':`${s.next.getMonth()+1}/${s.next.getDate()}復習予定`}`:'未設定';const left=s.n===4?'通常出題から休眠中':`習熟まで正解あと${s.remaining}回`;return `<div class="boki-qstats"><div class="boki-qstats-top"><b>習熟度 ${'★'.repeat(s.n)}${'☆'.repeat(4-s.n)} ${s.label}</b><span>${left}</span></div><div class="boki-qstats-grid"><span>回答 <b>${q.seen}</b>回</span><span>正解 <b>${q.correct}</b>回</span><span>正答率 <b>${s.acc}%</b></span><span>連続 <b>${q.streak}</b>回</span></div><div class="boki-qstats-next">${next}</div></div>`}
function injectQuestionStats(){const ctx=currentContext();if(!ctx)return;const page=(location.pathname.split('/').pop()||'').toLowerCase();let card=page==='q1.html'?document.getElementById('quizCard'):page==='q2.html'?document.getElementById('questionCard'):page==='q3.html'?document.getElementById('questionCard'):page==='daily.html'?document.getElementById('card'):null;if(!card)return;let old=card.querySelector('.boki-qstats');if(old)old.remove();card.insertAdjacentHTML('afterbegin',statsHtml(ctx))}
function injectCss(){if(document.getElementById('boki-mastery-css'))return;const st=document.createElement('style');st.id='boki-mastery-css';st.textContent=`
.boki-qstats{border:1px solid #d6e2ee;background:linear-gradient(135deg,#f7fbff,#fff);border-radius:13px;padding:9px 10px;margin:0 0 11px;color:#334b63}.boki-qstats-top{display:flex;justify-content:space-between;gap:8px;align-items:center;font-size:.75rem}.boki-qstats-top b{color:#1e5d98}.boki-qstats-top span{font-size:.68rem;color:#6c7d8f}.boki-qstats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:7px}.boki-qstats-grid span{background:#fff;border:1px solid #e0e7ef;border-radius:8px;padding:5px 3px;text-align:center;font-size:.65rem}.boki-qstats-grid b{font-size:.76rem}.boki-qstats-next{margin-top:5px;text-align:right;font-size:.65rem;color:#708195}.boki-mode-strip{display:flex;gap:7px;overflow:auto;padding:2px 1px 8px;scrollbar-width:none}.boki-mode-strip::-webkit-scrollbar{display:none}.boki-mode-chip{flex:0 0 auto;text-decoration:none;border:1px solid #cdd9e5;background:#fff;color:#35516e;border-radius:999px;padding:8px 11px;font-size:.75rem;font-weight:900}.boki-mode-chip.active{background:#176bc1;color:#fff;border-color:#176bc1}.boki-install-card{display:grid;grid-template-columns:46px 1fr auto;gap:10px;align-items:center;border:1px solid #cfe0ee;background:linear-gradient(135deg,#f1f9ff,#fff);border-radius:16px;padding:11px 12px;margin:11px 0}.boki-install-card .ico{width:44px;height:44px;border-radius:13px;background:#e4f2ff;display:grid;place-items:center;font-size:1.35rem}.boki-install-card b{display:block}.boki-install-card small{display:block;color:#66798d;font-size:.7rem}.boki-install-card button{border:0;border-radius:11px;background:#176bc1;color:#fff;min-height:42px;padding:0 12px;font-weight:900}.boki-mastery-section{margin:12px 0}.boki-mastery-grid{display:grid;gap:8px}.boki-mastery-row{border:1px solid #d9e3ed;border-radius:12px;padding:9px;background:#fff}.boki-mastery-row-top{display:flex;justify-content:space-between;gap:8px;font-size:.76rem}.boki-mastery-bar{height:8px;background:#edf1f5;border-radius:999px;overflow:hidden;margin-top:6px}.boki-mastery-bar i{display:block;height:100%;background:linear-gradient(90deg,#39ad64,#16864b)}
@media(max-width:420px){.boki-qstats-top{align-items:flex-start;flex-direction:column}.boki-qstats-grid{grid-template-columns:repeat(2,1fr)}.boki-install-card{grid-template-columns:42px 1fr}.boki-install-card button{grid-column:1/-1;width:100%}}
`;document.head.appendChild(st)}
function wrapRecorders(){const page=(location.pathname.split('/').pop()||'').toLowerCase();
 if(page==='q1.html'&&typeof window.record==='function'&&!window.record.__mastery){const orig=window.record;const w=function(id,skill,ok,sec,dont){const r=orig.apply(this,arguments);record('q1',q1Stable(id),!!ok,sec,!!dont,{skill,topic:skill});setTimeout(injectQuestionStats,0);return r};w.__mastery=true;window.record=w}
 if(page==='q2.html'&&typeof window.submitAnswer==='function'&&!window.submitAnswer.__mastery){const orig=window.submitAnswer;const w=function(user='',unknown=false,clicked=null){let z=null,ok=false,sec=0;try{z=session.list[session.index];sec=(Date.now()-session.start)/1000;ok=!unknown&&String(user)===String(z.answer)}catch(e){}const r=orig.apply(this,arguments);if(z)record('q2',z.id||`Q2:${hash(normalizeNumbers(z.title||z.transaction||''))}`,ok,sec,unknown,{topic:z.category||''});setTimeout(injectQuestionStats,0);return r};w.__mastery=true;window.submitAnswer=w}
 if(page==='q3.html'&&typeof window.recordResult==='function'&&!window.recordResult.__mastery){const orig=window.recordResult;const w=function(item,ok,sec,dont){const r=orig.apply(this,arguments);const id=item?.id||`Q3:${hash(normalizeNumbers(item?.title||item?.transaction||''))}`;record('q3',id,!!ok,sec,!!dont,{topic:item?.category||item?.skill||'',skill:item?.skill||''});setTimeout(injectQuestionStats,0);return r};w.__mastery=true;window.recordResult=w}
 if(page==='daily.html'&&typeof window.record==='function'&&!window.record.__mastery){const orig=window.record;const w=function(value,unknown=false){let z=null,ok=false,sec=0;try{z=list[idx];ok=!unknown&&value===z.answer;sec=Math.max(.1,(Date.now()-startAt)/1000)}catch(e){}const r=orig.apply(this,arguments);if(z)record(z.source||'daily',dailyId(z),ok,sec,unknown,{topic:z.topic||''});setTimeout(injectQuestionStats,0);return r};w.__mastery=true;window.record=w}
}
function observeQuestions(){const ids=['quizCard','questionCard','card'];ids.forEach(id=>{const el=document.getElementById(id);if(el){new MutationObserver(()=>setTimeout(injectQuestionStats,0)).observe(el,{childList:true,subtree:false})}});setTimeout(injectQuestionStats,50)}
function setupInstall(){if((location.pathname.split('/').pop()||'index.html')!=='index.html')return;const box=document.getElementById('pwaInstallCard');if(!box)return;const installed=matchMedia('(display-mode: standalone)').matches||navigator.standalone;if(installed){box.hidden=true;return}let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;box.hidden=false});const btn=box.querySelector('button');btn?.addEventListener('click',async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;return}alert('Chromeの「︙」メニューから「アプリをインストール」または「ホーム画面に追加」を選んでください。')});window.addEventListener('appinstalled',()=>{box.hidden=true;deferred=null});box.hidden=false}
function renderTop(){if((location.pathname.split('/').pop()||'index.html')!=='index.html')return;['q1','q2','q3'].forEach(m=>{const s=moduleSummary(m),el=document.querySelector(`[data-mastery-module="${m}"]`);if(!el)return;el.querySelector('.mtext').textContent=s.tracked?`習熟 ${s.pct}%・${s.mastered}/${s.tracked}問`:'まだ学習記録なし';el.querySelector('.mbar i').style.width=`${s.pct}%`;el.querySelector('.mweak').textContent=s.weak?`苦手 ${s.weak}問`:(s.due?`復習予定 ${s.due}問`:'')});const sums=['q1','q2','q3'].map(moduleSummary),tracked=sums.reduce((a,x)=>a+x.tracked,0),mastered=sums.reduce((a,x)=>a+x.mastered,0);const overall=document.getElementById('overallMastery');if(overall)overall.textContent=tracked?`${Math.round(mastered/tracked*100)}%`:'—';setupInstall()}
function renderManagement(){if((location.pathname.split('/').pop()||'')!=='management.html')return;if(document.getElementById('masteryOverview'))return;const anchor=document.querySelector('.cross-hero')||document.querySelector('.u-stats');if(!anchor)return;const sec=document.createElement('div');sec.id='masteryOverview';sec.className='boki-mastery-section';sec.innerHTML=`<div class="u-section-head"><h2>問題別の習熟度</h2><span>習熟問題は復習予定日まで休眠</span></div><div class="u-card"><div class="boki-mastery-grid">${['q1','q2','q3'].map(m=>{const s=moduleSummary(m);return`<div class="boki-mastery-row"><div class="boki-mastery-row-top"><b>${moduleNames[m]}</b><span>習熟 ${s.mastered}/${s.tracked}問・${s.pct}%　復習予定${s.due}問</span></div><div class="boki-mastery-bar"><i style="width:${s.pct}%"></i></div></div>`}).join('')}</div></div>`;anchor.insertAdjacentElement('afterend',sec)}
function setupDailyModes(){if((location.pathname.split('/').pop()||'')!=='daily.html')return;const mode=new URLSearchParams(location.search).get('mode')||localStorage.getItem('boki3_daily_mode')||'smart';localStorage.setItem('boki3_daily_mode',mode);const reason=document.querySelector('.reason-card');if(reason&&!document.getElementById('dailyModeStrip')){const strip=document.createElement('div');strip.id='dailyModeStrip';strip.className='boki-mode-strip';const modes=[['smart','おすすめ'],['due','復習予定'],['low','未習熟'],['wrong','苦手だけ'],['unlearned','未学習']];strip.innerHTML=modes.map(([k,l])=>`<a class="boki-mode-chip ${mode===k?'active':''}" href="daily.html?mode=${k}">${l}</a>`).join('');reason.insertAdjacentElement('afterend',strip)}
 try{const candidates=[];for(let i=0;i<14;i++){const xs=build();for(const x of xs){const id=dailyId(x);if(!candidates.some(y=>dailyId(y)===id))candidates.push(x)}}const ranked=candidates.map(x=>{const q=db.questions[key(x.source||'daily',dailyId(x))]||null;return{x,p:priority(q,mode)}}).filter(z=>z.p>-900).sort((a,b)=>b.p-a.p);let picked=ranked.slice(0,10).map(z=>z.x);if(picked.length<10){const fallback=candidates.filter(x=>!picked.some(y=>dailyId(y)===dailyId(x))).map(x=>{const q=db.questions[key(x.source||'daily',dailyId(x))]||null;return{x,p:priority(q,'smart')}}).filter(z=>z.p>-900).sort((a,b)=>b.p-a.p);picked=[...picked,...fallback.slice(0,10-picked.length).map(z=>z.x)]}if(picked.length){list=shuffle(picked).slice(0,10);idx=0;responses={};const lab=document.querySelector('.daily-hero p');if(lab)lab.textContent=mode==='due'?'忘却曲線に基づく復習予定問題を優先します。':mode==='low'?'習熟していない問題だけを優先します。':mode==='wrong'?`誤答${readSettings().wrongThreshold}回以上の苦手問題を優先します。`:mode==='unlearned'?'まだ解いていない問題を優先します。':'弱点・未学習・復習予定を自動配分します。'}}catch(e){}
}
function bootstrap(){injectCss();migrate();wrapRecorders();observeQuestions();renderTop();renderManagement();setupDailyModes();save()}
window.BOKI_MASTERY={version:1,get,record,level,isMastered,due,priority,moduleSummary,statusText,settings:readSettings,store:()=>db,rebuild:()=>{db=safe(STORE,{version:1,questions:{},modules:{}});return db}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bootstrap,0));else setTimeout(bootstrap,0);
})();
