(function(){
'use strict';
const page=(location.pathname.split('/').pop()||'').toLowerCase();
const ready=fn=>{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(fn,90));else setTimeout(fn,90)};
function hash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
const norm=s=>String(s||'').replace(/[¥￥]?\s*\d[\d,]*(?:\.\d+)?/g,'#').replace(/\s+/g,' ').trim();
function eligible(module,id){try{return window.BOKI_MASTERY.priority(window.BOKI_MASTERY.get(module,id),'smart')>-900}catch(e){return true}}
function masteredMessage(card,title='このモードは習熟済みです'){if(!card)return;card.innerHTML=`<div style="text-align:center;padding:28px 12px"><div style="font-size:2.3rem">🌟</div><h2>${title}</h2><p style="color:#6d7e90;line-height:1.7">復習予定日までは通常出題から休ませます。<br>「復習予定」または別の未習熟分野に進みましょう。</p><div style="display:grid;gap:8px;margin-top:14px"><a href="daily.html?mode=due" style="display:grid;place-items:center;min-height:50px;border-radius:13px;background:#176bc1;color:#fff;text-decoration:none;font-weight:900">復習予定を確認</a><a href="index.html" style="display:grid;place-items:center;min-height:48px;border-radius:13px;background:#edf2f6;color:#40546b;text-decoration:none;font-weight:900">ホームへ</a></div></div>`}
function bootQ1(){if(typeof session==='undefined'||typeof nav!=='function')return;
 function idOf(z,mode){if(mode==='classify')return`ACC:${z.name}`;if(mode==='dc')return`DC:${z.x?.name}:${z.inc?'up':'down'}`;if(mode==='j4')return`J4:${hash(norm(z.body))}`;if(mode==='drop')return`JD:${hash(norm(z.body))}`;if(mode==='phrase')return`PH:${z.id}`;return`Q1:${hash(norm(JSON.stringify(z)))}`}
 const defs=[['startClassify','classify','renderClassify'],['startDebitCredit','dc','renderDC'],['startJournal4','j4','renderJ4'],['startDropdown','drop','renderDrop'],['startPhraseTrainer','phrase','renderPhrase']];
 defs.forEach(([name,mode,renderer])=>{const orig=window[name];if(typeof orig!=='function'||orig.__nativeMastery)return;const w=function(){const r=orig.apply(this,arguments);try{const f=(session.list||[]).filter(z=>eligible('q1',idOf(z,session.mode||mode)));if(!f.length){session.list=[];document.getElementById('progress').textContent='0/0';document.getElementById('timer').textContent='—';masteredMessage(document.getElementById('quizCard'));return r}if(f.length!==session.list.length){session.list=f;session.index=0;session.responses={};const fn=window[renderer];if(typeof fn==='function')fn()}}catch(e){}return r};w.__nativeMastery=true;window[name]=w});
}
function bootQ2(){if(typeof window.startMode!=='function'||typeof session==='undefined')return;const orig=window.startMode;if(orig.__nativeMastery)return;const w=function(mode,customList=null){const r=orig.apply(this,arguments);if(customList)return r;try{const f=(session.list||[]).filter(z=>eligible('q2',z.id));if(!f.length){session.list=[];const p=document.getElementById('progressText');if(p)p.textContent='0 / 0';const t=document.getElementById('timerText');if(t)t.textContent='—';masteredMessage(document.getElementById('questionCard'));return r}if(f.length!==session.list.length){session.list=f;session.index=0;session.correct=0;session.answered=false;renderQuestion()}}catch(e){}return r};w.__nativeMastery=true;window.startMode=w}
function bootQ3(){if(typeof window.startMode!=='function'||typeof session==='undefined')return;const orig=window.startMode;if(orig.__nativeMastery)return;const w=function(mode,custom=null){const r=orig.apply(this,arguments);if(custom)return r;try{const f=(session.list||[]).filter(z=>eligible('q3',z.id));if(!f.length){session.list=[];const p=document.getElementById('progressText');if(p)p.textContent='0 / 0';const t=document.getElementById('timerText');if(t)t.textContent='—';masteredMessage(document.getElementById('questionCard'));return r}if(f.length!==session.list.length){session.list=f;session.index=0;session.correct=0;session.answered=false;renderQuestion()}}catch(e){}return r};w.__nativeMastery=true;window.startMode=w}
ready(()=>{if(!window.BOKI_MASTERY)return;if(page==='q1.html')bootQ1();if(page==='q2.html')bootQ2();if(page==='q3.html')bootQ3()});
})();
