(function(){
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='daily.html')return;
const mode=()=>new URLSearchParams(location.search).get('mode')||'smart';let listDone=false,recordDone=false;
function rank(c){try{const q=window.BOKI_MASTERY?.get?.(c.source,c.practicalId,{topic:c.topic,skill:'実戦連結'});return window.BOKI_MASTERY?.priority?.(q,mode())??-999}catch(e){return-999}}
function shape(c){return{source:c.source,topic:`実戦連結・${c.topic}`,q:c.q,answer:c.answer,choices:[...c.choices],display:typeof shuffle==='function'?shuffle([...c.choices]):[...c.choices],exp:c.exp,id:c.practicalId,practicalId:c.practicalId,practicalTopic:c.topic}}
function update(){try{const r=document.getElementById('reasons');if(r&&!r.querySelector('[data-practical-reason]'))r.insertAdjacentHTML('beforeend','<span data-practical-reason>初見資料の実戦問題も選定</span>');const counts={q1:0,q2:0,q3:0};list.forEach(x=>{if(counts[x.source]!=null)counts[x.source]++});const mix=document.getElementById('mix');if(mix)mix.innerHTML=Object.entries(counts).filter(([,n])=>n).map(([k,n])=>`<span>${areaLabel[k]} ${n}問</span>`).join('')}catch(e){}}
function patchList(){if(listDone||typeof list==='undefined'||!Array.isArray(list)||!window.BOKI_PRACTICAL_DAILY_POOL||!window.BOKI_MASTERY)return false;const ranked=window.BOKI_PRACTICAL_DAILY_POOL.map(c=>({c,p:rank(c)})).filter(x=>x.p>-900).sort((a,b)=>b.p-a.p);if(!ranked.length){listDone=true;update();return true}const item=shape(ranked[0].c),strict=['due','wrong','unlearned'].includes(mode());if(!list.some(x=>x.practicalId===item.practicalId)){if(strict&&list.length<10)list.push(item);else{let at=-1;for(let i=list.length-1;i>=0;i--){if(list[i].source===item.source&&!list[i].practicalId&&!list[i].coverageId){at=i;break}}if(at<0)for(let i=list.length-1;i>=0;i--){if(!list[i].practicalId&&!list[i].coverageId){at=i;break}}if(at>=0)list[at]=item}if(list.length>10)list=list.slice(0,10)}listDone=true;update();return true}
function patchRecord(){if(recordDone||typeof record!=='function'||!window.BOKI_MASTERY)return false;const orig=record;const w=function(value,unknown=false){let x=null,ok=false;try{x=list[idx];ok=!unknown&&value===x.answer}catch(e){}const r=orig.apply(this,arguments);if(x?.practicalId){try{window.BOKI_MASTERY.record(x.source,x.practicalId,ok,0,!!unknown,{topic:x.practicalTopic||x.topic,skill:'実戦連結'})}catch(e){}}return r};w.__practicalDaily=true;window.record=w;recordDone=true;return true}
function boot(n=0){const a=patchList(),b=patchRecord();if((!a||!b)&&n<45)return setTimeout(()=>boot(n+1),120);setTimeout(update,600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>boot(),850),{once:true});else setTimeout(()=>boot(),850);
})();