(function(){
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='questions.html')return;
function stat(s){const rs=s.steps.map((_,i)=>window.BOKI_MASTERY?.get?.(s.module,`W3:${s.id}:${i+1}`,{topic:s.name,skill:'実戦連結'})).filter(Boolean),seen=rs.reduce((a,q)=>a+Number(q.seen||0),0),correct=rs.reduce((a,q)=>a+Number(q.correct||0),0),wrong=rs.reduce((a,q)=>a+Number(q.wrong||0),0),acc=seen?Math.round(correct/seen*100):0,mastered=rs.length&&rs.every(q=>window.BOKI_MASTERY?.isMastered?.(q));let status='new',label='未回答';if(seen){if(mastered){status='mastered';label='習熟'}else if((seen>=3&&acc<60)||wrong>=3){status='weak';label='苦手'}else if(seen>=Math.max(2,Math.ceil(rs.length*.6))&&acc>=75){status='settling';label='定着中'}else{status='learning';label='学習中'}}return{seen,correct,wrong,acc,mastered,status,label}}
function num(id){return Number((document.getElementById(id)?.textContent||'0').replace(/[^0-9]/g,''))||0}
function base(id){const e=document.getElementById(id);if(!e)return 0;if(e.dataset.practicalBase==null)e.dataset.practicalBase=String(num(id));return Number(e.dataset.practicalBase||0)}
function updateTotals(stats){const total=base('totalN')+stats.length,answered=base('answeredN')+stats.filter(x=>x.seen>0).length,mastered=base('masteredN')+stats.filter(x=>x.mastered).length,state=k=>stats.filter(x=>x.status===k).length;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('totalN',total);set('answeredN',answered);set('remainingN',Math.max(0,total-answered));[['newN','new'],['weakN','weak'],['learningN','learning'],['settlingN','settling'],['masteredN','mastered']].forEach(([id,k])=>set(id,base(id)+state(k)));const cp=total?Math.round(answered/total*100):0,mp=total?Math.round(mastered/total*100):0;set('coverageText',cp+'%');set('masteryText',mp+'%');const cb=document.getElementById('coverageBar'),mb=document.getElementById('masteryBar');if(cb)cb.style.width=cp+'%';if(mb)mb.style.width=mp+'%'}
function currentFilter(){return document.querySelector('#filters .filter.on')?.dataset.filter||'all'}
function filter(){const sec=document.getElementById('practicalSupplement');if(!sec)return;const q=(document.getElementById('search')?.value||'').trim().toLowerCase(),f=currentFilter();let n=0;sec.querySelectorAll('.item').forEach(r=>{const okQ=!q||r.textContent.toLowerCase().includes(q),okF=f==='all'||(f==='due'?false:r.dataset.status===f);r.style.display=okQ&&okF?'grid':'none';if(okQ&&okF)n++});sec.style.display=n?'block':'none'}
function bindSequence(sec){sec.querySelectorAll('.item a').forEach(a=>{a.onclick=e=>{e.preventDefault();const row=a.closest('.item'),visible=[...sec.querySelectorAll('.item')].filter(r=>r.style.display!=='none'),at=visible.indexOf(row),ids=visible.slice(Math.max(0,at)).map(r=>r.dataset.practicalId).filter(Boolean);if(!ids.length)return;location.href=`practical.html?book=1&topic=${encodeURIComponent(ids[0])}&seq=${encodeURIComponent(ids.join(','))}`}})}
function mount(){const C=window.BOKI_PRACTICAL_CATALOG;if(!C||!window.BOKI_MASTERY)return setTimeout(mount,150);const catalog=document.getElementById('catalog');if(!catalog)return;document.getElementById('practicalSupplement')?.remove();const stats=C.map(stat),sec=document.createElement('section');sec.id='practicalSupplement';sec.style.cssText='margin:12px 0;border:1px solid #bfd5e8;background:#f8fbff;border-radius:17px;overflow:hidden';sec.innerHTML=`<div style="background:linear-gradient(135deg,#173b67,#2b78ba);color:#fff;padding:12px 13px"><b style="display:block">実戦連結｜初見資料に強くなる</b><small style="font-size:.7rem;opacity:.94">一問一答ではなく、資料→仕訳→帳簿→計算を数STEPつなげます。絞り込み時も、開始時に見えていた順番を固定します。</small></div><div style="padding:2px 9px 9px">${C.map((s,i)=>{const z=stats[i];return `<div class="item" data-status="${z.status}" data-practical-id="${s.id}"><a href="practical.html?book=1&topic=${encodeURIComponent(s.id)}" style="text-decoration:none;color:inherit;display:contents"><div><div class="item-name"><span style="display:inline-block;background:#e7f1fb;color:#235f91;border-radius:999px;padding:3px 6px;font-size:.61rem;font-weight:900;margin-right:4px">実戦</span>${s.name}</div><div class="item-sub">${s.desc}・${s.steps.length}STEP</div><div class="metric"><span>回答 ${z.seen}回</span><span>正答率 ${z.seen?z.acc+'%':'—'}</span></div></div><span class="status ${z.status}">${z.label}</span></a></div>`}).join('')}</div>`;catalog.insertAdjacentElement('beforebegin',sec);updateTotals(stats);filter();bindSequence(sec);const search=document.getElementById('search');if(search&&!search.__practical){search.addEventListener('input',filter);search.__practical=true}document.querySelectorAll('#filters .filter').forEach(b=>{if(!b.__practical){b.addEventListener('click',()=>setTimeout(filter,10));b.__practical=true}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,1500),{once:true});else setTimeout(mount,1500);window.addEventListener('pageshow',()=>setTimeout(mount,1300));
})();