(function(){
'use strict';
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
function addStyle(){if(document.getElementById('public-info-style'))return;const s=document.createElement('style');s.id='public-info-style';s.textContent='.public-info-note{margin:16px 10px 82px;padding:10px 12px;border:1px solid #d7e1eb;border-radius:12px;background:#f8fafc;color:#637386;font-size:.69rem;line-height:1.6;text-align:center}.public-info-note a{color:#176bc1;font-weight:900;text-decoration:none}.public-info-card{display:grid;grid-template-columns:42px 1fr 22px;gap:9px;align-items:center;border:1px solid var(--u-line,#d7e1eb);border-radius:14px;padding:11px 12px;margin-top:12px;background:#fff;text-decoration:none;color:var(--u-text,#26384a)}.public-info-card .pi-icon{width:40px;height:40px;border-radius:11px;background:#eef5fb;display:grid;place-items:center;font-size:1.15rem}.public-info-card b{display:block}.public-info-card small{display:block;margin-top:2px;color:var(--u-muted,#6a7a8b);font-size:.7rem;line-height:1.45}.public-info-card .pi-go{font-size:1.5rem;color:#176bc1}.public-unofficial{display:inline-block;margin-left:6px;border-radius:999px;padding:2px 6px;background:#eef5fb;color:#245d91;font-size:.6rem;font-weight:900;vertical-align:middle}';document.head.appendChild(s)}
function changeCopy(){const sub=document.querySelector('.app-brand-sub');if(sub&&sub.textContent.includes('しっかり合格'))sub.textContent='やさしく学んで、合格をめざす';const title=document.querySelector('.app-brand-title');if(title&&!title.querySelector('.public-unofficial'))title.insertAdjacentHTML('beforeend','<span class="public-unofficial">非公式</span>')}
function addSettingsLink(){if(page!=='settings.html'||document.getElementById('publicInfoSettings'))return;const main=document.querySelector('main.u-page')||document.querySelector('main');if(!main)return;const a=document.createElement('a');a.id='publicInfoSettings';a.href='about.html';a.className='public-info-card';a.innerHTML='<span class="pi-icon">ⓘ</span><span><b>このアプリについて</b><small>運営者・非公式表示・プライバシー・免責・問い合わせ</small></span><span class="pi-go">›</span>';main.appendChild(a)}
function addNotice(){if(page==='about.html'||document.getElementById('publicInfoNotice'))return;const main=document.querySelector('main');if(!main)return;const d=document.createElement('div');d.id='publicInfoNotice';d.className='public-info-note';d.innerHTML='個人制作の非公式学習アプリです。日本商工会議所・各地商工会議所の公式教材ではありません。 <a href="about.html">このアプリについて</a>';main.insertAdjacentElement('afterend',d)}
function run(){addStyle();changeCopy();addSettingsLink();addNotice()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();window.addEventListener('pageshow',run);
})();
