(function(){
'use strict';
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
function addStyle(){if(document.getElementById('publication-ux-style'))return;const s=document.createElement('style');s.id='publication-ux-style';s.textContent='.ux-input-progress{display:block;margin-top:2px;font-size:.62rem;opacity:.78;font-weight:800}.ux-scroll-hint{display:none;margin:5px 0 7px;padding:6px 9px;border-radius:9px;background:#eef6fd;color:#285a89;font-size:.7rem;font-weight:850;text-align:right}.ux-scroll-hint.show{display:block}.ux-next-review{display:grid;grid-template-columns:38px 1fr 22px;gap:9px;align-items:center;margin:13px 0;padding:12px 13px;border-radius:14px;background:linear-gradient(135deg,#176bc1,#24558b);color:#fff;text-decoration:none;text-align:left;box-shadow:0 7px 18px rgba(25,82,151,.18)}.ux-next-review .ux-review-icon{width:36px;height:36px;border-radius:10px;background:rgba(255,255,255,.16);display:grid;place-items:center;font-weight:950}.ux-next-review b{display:block}.ux-next-review small{display:block;margin-top:2px;font-size:.7rem;opacity:.92}.ux-next-review .ux-review-go{font-size:1.5rem;font-weight:950}@media(max-width:760px){.ux-scroll-hint.show{display:block}.tbl th:first-child,.tbl td:first-child,.fs th:first-child,.fs td:first-child,.cbt-table th:first-child,.cbt-table td:first-child{position:sticky;left:0;z-index:2;background:#f7f9fc}.tbl th:first-child,.fs th:first-child,.cbt-table th:first-child{z-index:3;background:#eaf0f6}}';document.head.appendChild(s)}
function fixQ1RecommendedCount(){if(page!=='q1.html'||typeof window.startClassify!=='function'||window.startClassify.__uxFixed)return;const original=window.startClassify;function wrapped(kind){original(kind);try{if(kind==='basic'&&typeof session!=='undefined'&&Array.isArray(session.list)&&session.list.length>10){session.list=session.list.slice(0,10);if(typeof renderClassify==='function')renderClassify()}}catch(e){}}wrapped.__uxFixed=true;window.startClassify=wrapped}
function controlFilled(el){if(!el||el.disabled)return true;return String(el.value??'').trim()!==''}
function mockCounts(){if(page!=='mock.html')return null;const out={};for(const id of ['q1','q2','q3']){const root=document.getElementById(id);if(!root){out[id]={done:0,total:0};continue}if(id==='q1'){const cards=[...root.querySelectorAll('.qcard')];out[id]={total:cards.length,done:cards.filter(card=>{const c=[...card.querySelectorAll('input,select')].filter(x=>!x.disabled);return c.length>0&&c.every(controlFilled)}).length}}else{const controls=[...root.querySelectorAll('input,select')].filter(x=>!x.disabled&&x.offsetParent!==null);out[id]={total:controls.length,done:controls.filter(controlFilled).length}}}return out}
function updateMockProgress(){const counts=mockCounts();if(!counts)return;for(const id of ['q1','q2','q3']){const b=document.querySelector(`.section-nav button[data-sec="${id}"]`);if(!b)continue;let p=b.querySelector('.ux-input-progress');if(!p){p=document.createElement('span');p.className='ux-input-progress';b.appendChild(p)}const x=counts[id],txt=x.total?`入力 ${x.done}/${x.total}`:'入力 —';if(p.textContent!==txt)p.textContent=txt}}
function setupMockFinishGuard(){if(page!=='mock.html')return;const finish=document.getElementById('finish');if(!finish||finish.dataset.uxGuard)return;finish.dataset.uxGuard='1';finish.addEventListener('click',e=>{if(finish.dataset.uxConfirmed==='1'){finish.dataset.uxConfirmed='';return}const c=mockCounts();if(!c)return;const blank=Object.values(c).reduce((n,x)=>n+Math.max(0,x.total-x.done),0);if(blank<=0)return;e.preventDefault();e.stopImmediatePropagation();const ok=window.confirm(`未入力が ${blank} か所あります。\nこのまま終了して採点しますか？`);if(ok){finish.dataset.uxConfirmed='1';finish.click()}},true);window.addEventListener('beforeunload',e=>{try{if(typeof state!=='undefined'&&state.started&&!state.ended){e.preventDefault();e.returnValue=''}}catch(err){}})}
function enhanceScrollableTables(){if(!['q2-cbt.html','q3-cbt.html','mock.html'].includes(page))return;document.querySelectorAll('.wrap,.table-wrap').forEach(w=>{if(w.dataset.uxScroll)return;const table=w.querySelector('table');if(!table)return;w.dataset.uxScroll='1';const h=document.createElement('div');h.className='ux-scroll-hint';h.textContent='← 表は横にスクロールできます →';w.parentNode.insertBefore(h,w);const refresh=()=>{const needs=w.scrollWidth>w.clientWidth+8;h.classList.toggle('show',needs&&w.scrollLeft<8)};w.addEventListener('scroll',refresh,{passive:true});setTimeout(refresh,0);window.addEventListener('resize',refresh,{passive:true})})}
function parseRate(txt){const m=String(txt||'').match(/([\d.]+)\s*\/\s*([\d.]+)/);if(!m)return null;const a=Number(m[1]),b=Number(m[2]);return b>0?a/b:null}
function addReviewLink(host,before,area,label,detail){if(!host||host.querySelector('.ux-next-review'))return;const href=area==='q1'?'q1-cbt.html':area==='q2'?'q2-cbt.html':'q3-cbt.html';const a=document.createElement('a');a.className='ux-next-review';a.href=href;a.innerHTML=`<span class="ux-review-icon">↻</span><span><b>${label}</b><small>${detail}</small></span><span class="ux-review-go">›</span>`;host.insertBefore(a,before||null)}
function enhanceMockResult(){if(page!=='mock.html')return;const host=document.querySelector('#result.show .result-main');if(!host||host.querySelector('.ux-next-review'))return;const parts=[...host.querySelectorAll('.part')].map((el,i)=>({area:['q1','q2','q3'][i],rate:parseRate(el.querySelector('b')?.textContent),name:el.querySelector('span')?.textContent||`第${i+1}問`})).filter(x=>x.rate!=null);if(!parts.length)return;parts.sort((a,b)=>a.rate-b.rate);const w=parts[0];addReviewLink(host,host.querySelector('.result-actions'),w.area,`${w.name}を重点復習する`,'今回もっとも得点率が低かった大問を、本番形式で反復します。')}
function enhanceDailyResult(){if(page!=='daily.html')return;const host=document.querySelector('#quiz .qcard.result');if(!host||host.querySelector('.ux-next-review'))return;const rows=[...host.querySelectorAll('.result-grid > div')].map((el,i)=>({area:['q1','q2','q3'][i],rate:parseRate(el.querySelector('b')?.textContent),name:el.querySelector('span')?.textContent||`第${i+1}問`})).filter(x=>x.rate!=null);if(!rows.length)return;rows.sort((a,b)=>a.rate-b.rate);const w=rows[0],actions=host.querySelector('.actions');addReviewLink(host,actions,w.area,`${w.name}を今すぐ復習する`,'今日の10問で正答率が低かった大問へ、そのまま進みます。');if(actions){const primary=actions.querySelector('.primary');if(primary){primary.classList.remove('primary');primary.classList.add('secondary');primary.textContent='別の10問を作る'}}}
function enhanceResults(){enhanceMockResult();enhanceDailyResult()}
function run(){addStyle();fixQ1RecommendedCount();updateMockProgress();setupMockFinishGuard();enhanceScrollableTables();enhanceResults()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
window.addEventListener('pageshow',run);
document.addEventListener('input',()=>{if(page==='mock.html')updateMockProgress()});document.addEventListener('change',()=>{if(page==='mock.html')updateMockProgress()});
const mo=new MutationObserver(()=>{if(page==='mock.html')updateMockProgress();if(['q2-cbt.html','q3-cbt.html','mock.html'].includes(page))enhanceScrollableTables();if(page==='q1.html')fixQ1RecommendedCount();enhanceResults()});if(document.documentElement)mo.observe(document.documentElement,{subtree:true,childList:true});
})();