(function(){
'use strict';
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
function addStyle(){if(document.getElementById('publication-ux-style'))return;const s=document.createElement('style');s.id='publication-ux-style';s.textContent='.ux-input-progress{display:block;margin-top:2px;font-size:.62rem;opacity:.78;font-weight:800}.ux-scroll-hint{display:none;margin:5px 0 7px;padding:6px 9px;border-radius:9px;background:#eef6fd;color:#285a89;font-size:.7rem;font-weight:850;text-align:right}.ux-scroll-hint.show{display:block}@media(max-width:760px){.ux-scroll-hint.show{display:block}.tbl th:first-child,.tbl td:first-child,.fs th:first-child,.fs td:first-child,.cbt-table th:first-child,.cbt-table td:first-child{position:sticky;left:0;z-index:2;background:#f7f9fc}.tbl th:first-child,.fs th:first-child,.cbt-table th:first-child{z-index:3;background:#eaf0f6}}';document.head.appendChild(s)}
function fixQ1RecommendedCount(){if(page!=='q1.html'||typeof window.startClassify!=='function'||window.startClassify.__uxFixed)return;const original=window.startClassify;function wrapped(kind){original(kind);try{if(kind==='basic'&&typeof session!=='undefined'&&Array.isArray(session.list)&&session.list.length>10){session.list=session.list.slice(0,10);if(typeof renderClassify==='function')renderClassify()}}catch(e){}}wrapped.__uxFixed=true;window.startClassify=wrapped}
function controlFilled(el){if(!el||el.disabled)return true;return String(el.value??'').trim()!==''}
function mockCounts(){if(page!=='mock.html')return null;const out={};for(const id of ['q1','q2','q3']){const root=document.getElementById(id);if(!root){out[id]={done:0,total:0};continue}if(id==='q1'){const cards=[...root.querySelectorAll('.qcard')];out[id]={total:cards.length,done:cards.filter(card=>{const c=[...card.querySelectorAll('input,select')].filter(x=>!x.disabled);return c.length>0&&c.every(controlFilled)}).length}}else{const controls=[...root.querySelectorAll('input,select')].filter(x=>!x.disabled&&x.offsetParent!==null);out[id]={total:controls.length,done:controls.filter(controlFilled).length}}}return out}
function updateMockProgress(){const counts=mockCounts();if(!counts)return;for(const id of ['q1','q2','q3']){const b=document.querySelector(`.section-nav button[data-sec="${id}"]`);if(!b)continue;let p=b.querySelector('.ux-input-progress');if(!p){p=document.createElement('span');p.className='ux-input-progress';b.appendChild(p)}const x=counts[id],txt=x.total?`入力 ${x.done}/${x.total}`:'入力 —';if(p.textContent!==txt)p.textContent=txt}}
function setupMockFinishGuard(){if(page!=='mock.html')return;const finish=document.getElementById('finish');if(!finish||finish.dataset.uxGuard)return;finish.dataset.uxGuard='1';finish.addEventListener('click',e=>{if(finish.dataset.uxConfirmed==='1'){finish.dataset.uxConfirmed='';return}const c=mockCounts();if(!c)return;const blank=Object.values(c).reduce((n,x)=>n+Math.max(0,x.total-x.done),0);if(blank<=0)return;e.preventDefault();e.stopImmediatePropagation();const ok=window.confirm(`未入力が ${blank} か所あります。\nこのまま終了して採点しますか？`);if(ok){finish.dataset.uxConfirmed='1';finish.click()}},true);window.addEventListener('beforeunload',e=>{try{if(typeof state!=='undefined'&&state.started&&!state.ended){e.preventDefault();e.returnValue=''}}catch(err){}})}
function enhanceScrollableTables(){if(!['q2-cbt.html','q3-cbt.html','mock.html'].includes(page))return;document.querySelectorAll('.wrap,.table-wrap').forEach(w=>{if(w.dataset.uxScroll)return;const table=w.querySelector('table');if(!table)return;w.dataset.uxScroll='1';const h=document.createElement('div');h.className='ux-scroll-hint';h.textContent='← 表は横にスクロールできます →';w.parentNode.insertBefore(h,w);const refresh=()=>{const needs=w.scrollWidth>w.clientWidth+8;h.classList.toggle('show',needs&&w.scrollLeft<8)};w.addEventListener('scroll',refresh,{passive:true});setTimeout(refresh,0);window.addEventListener('resize',refresh,{passive:true})})}
function run(){addStyle();fixQ1RecommendedCount();updateMockProgress();setupMockFinishGuard();enhanceScrollableTables()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
window.addEventListener('pageshow',run);
document.addEventListener('input',()=>{if(page==='mock.html')updateMockProgress()});document.addEventListener('change',()=>{if(page==='mock.html')updateMockProgress()});
const mo=new MutationObserver(()=>{if(page==='mock.html')updateMockProgress();if(['q2-cbt.html','q3-cbt.html','mock.html'].includes(page))enhanceScrollableTables();if(page==='q1.html')fixQ1RecommendedCount()});if(document.documentElement)mo.observe(document.documentElement,{subtree:true,childList:true});
})();