(function(){
'use strict';
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
function addStyle(){if(document.getElementById('publication-ux-style'))return;const s=document.createElement('style');s.id='publication-ux-style';s.textContent='.ux-input-progress{display:block;margin-top:2px;font-size:.62rem;opacity:.78;font-weight:800}.ux-scroll-hint{display:none;margin:5px 0 7px;padding:6px 9px;border-radius:9px;background:#eef6fd;color:#285a89;font-size:.7rem;font-weight:850;text-align:right}.ux-scroll-hint.show{display:block}.ux-next-review{display:grid;grid-template-columns:38px 1fr 22px;gap:9px;align-items:center;margin:13px 0;padding:12px 13px;border-radius:14px;background:linear-gradient(135deg,#176bc1,#24558b);color:#fff;text-decoration:none;text-align:left;box-shadow:0 7px 18px rgba(25,82,151,.18)}.ux-next-review .ux-review-icon{width:36px;height:36px;border-radius:10px;background:rgba(255,255,255,.16);display:grid;place-items:center;font-weight:950}.ux-next-review b{display:block}.ux-next-review small{display:block;margin-top:2px;font-size:.7rem;opacity:.92}.ux-next-review .ux-review-go{font-size:1.5rem;font-weight:950}.ux-beginner-alt{display:block;text-align:center;margin:8px 0 2px;color:#52697f;font-size:.74rem;font-weight:850;text-decoration:none}.ux-cbt-helper{position:sticky;top:58px;z-index:18;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;margin:0 0 10px;padding:8px 10px;border:1px solid #cfdbe7;border-radius:12px;background:rgba(255,255,255,.96);box-shadow:0 4px 14px rgba(28,58,88,.08);backdrop-filter:blur(8px)}.ux-cbt-helper b{display:block;font-size:.82rem}.ux-cbt-helper small{display:block;color:#65758a;font-size:.68rem}.ux-cbt-helper button{border:0;border-radius:10px;min-height:42px;padding:0 12px;background:#173b67;color:#fff;font-weight:900}.ux-cbt-helper button:disabled{background:#dbe4ec;color:#607286}.ux-focus-row{outline:3px solid rgba(47,111,173,.22);outline-offset:-3px;background:#f8fbff!important}.ux-focus-box{box-shadow:0 0 0 3px rgba(47,111,173,.14)!important}@media(max-width:760px){.ux-scroll-hint.show{display:block}.tbl th:first-child,.tbl td:first-child,.fs th:first-child,.fs td:first-child,.cbt-table th:first-child,.cbt-table td:first-child,.tb th:first-child,.tb td:first-child,.ws th:first-child,.ws td:first-child{position:sticky;left:0;z-index:2;background:#f7f9fc}.tbl th:first-child,.fs th:first-child,.cbt-table th:first-child,.tb th:first-child,.ws th:first-child{z-index:3;background:#eaf0f6}.ux-cbt-helper{top:54px;margin-left:-2px;margin-right:-2px}.ux-cbt-helper button{padding:0 10px}}';document.head.appendChild(s)}
function safeJson(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch(e){return null}}
function answeredCount(){let n=0;for(const k of ['boki3_q1_trainer_v1','boki3trainer_v2','boki3_q3_trainer_v1','boki3_cross_learning_v1']){const d=safeJson(k);if(d)n+=Number(d.answered||0)}return n}
function simplifyBeginnerHome(){if(page!=='index.html'||document.body.dataset.uxBeginnerDone)return;document.body.dataset.uxBeginnerDone='1';if(answeredCount()>=5)return;const card=document.querySelector('.personal-daily'),picker=document.querySelector('.mode-picker'),cont=document.getElementById('continueBtn');if(cont)cont.style.display='none';if(picker)picker.style.display='none';if(card){card.href='understand.html';const mark=card.querySelector('.mark'),strong=card.querySelector('strong'),small=card.querySelector('small'),mix=card.querySelector('.mixline');if(mark)mark.textContent='1';if(strong)strong.textContent='初めてなら ここから';if(small)small.textContent='まず「何が増えた・減った？」から、5要素→借方・貸方→仕訳の流れをつかみます。';if(mix)mix.innerHTML='<i>5要素</i><i>借方・貸方</i><i>仕訳の流れ</i>';if(!card.nextElementSibling?.classList?.contains('ux-beginner-alt')){const a=document.createElement('a');a.className='ux-beginner-alt';a.href='daily.html?mode=smart';a.textContent='すぐ問題を解きたい方：今日の10問 →';card.insertAdjacentElement('afterend',a)}}}
function fixQ1RecommendedCount(){if(page!=='q1.html'||typeof window.startClassify!=='function'||window.startClassify.__uxFixed)return;const original=window.startClassify;function wrapped(kind){original(kind);try{if(kind==='basic'&&typeof session!=='undefined'&&Array.isArray(session.list)&&session.list.length>10){session.list=session.list.slice(0,10);if(typeof renderClassify==='function')renderClassify()}}catch(e){}}wrapped.__uxFixed=true;window.startClassify=wrapped}
function controlFilled(el){if(!el||el.disabled)return true;return String(el.value??'').trim()!==''}
function mockCounts(){if(page!=='mock.html')return null;const out={};for(const id of ['q1','q2','q3']){const root=document.getElementById(id);if(!root){out[id]={done:0,total:0};continue}if(id==='q1'){const cards=[...root.querySelectorAll('.qcard')];out[id]={total:cards.length,done:cards.filter(card=>{const c=[...card.querySelectorAll('input,select')].filter(x=>!x.disabled);return c.length>0&&c.every(controlFilled)}).length}}else{const controls=[...root.querySelectorAll('input,select')].filter(x=>!x.disabled&&x.offsetParent!==null);out[id]={total:controls.length,done:controls.filter(controlFilled).length}}}return out}
function updateMockProgress(){const counts=mockCounts();if(!counts)return;for(const id of ['q1','q2','q3']){const b=document.querySelector(`.section-nav button[data-sec="${id}"]`);if(!b)continue;let p=b.querySelector('.ux-input-progress');if(!p){p=document.createElement('span');p.className='ux-input-progress';b.appendChild(p)}const x=counts[id],txt=x.total?`入力 ${x.done}/${x.total}`:'入力 —';if(p.textContent!==txt)p.textContent=txt}}
function setupMockFinishGuard(){if(page!=='mock.html')return;const finish=document.getElementById('finish');if(!finish||finish.dataset.uxGuard)return;finish.dataset.uxGuard='1';finish.addEventListener('click',e=>{if(finish.dataset.uxConfirmed==='1'){finish.dataset.uxConfirmed='';return}const c=mockCounts();if(!c)return;const blank=Object.values(c).reduce((n,x)=>n+Math.max(0,x.total-x.done),0);if(blank<=0)return;e.preventDefault();e.stopImmediatePropagation();const ok=window.confirm(`未入力が ${blank} か所あります。\nこのまま終了して採点しますか？`);if(ok){finish.dataset.uxConfirmed='1';finish.click()}},true);window.addEventListener('beforeunload',e=>{try{if(typeof state!=='undefined'&&state.started&&!state.ended){e.preventDefault();e.returnValue=''}}catch(err){}})}
function enhanceScrollableTables(){if(!['q2-cbt.html','q3-cbt.html','mock.html'].includes(page))return;document.querySelectorAll('.wrap,.table-wrap').forEach(w=>{if(w.dataset.uxScroll)return;const table=w.querySelector('table');if(!table)return;w.dataset.uxScroll='1';const h=document.createElement('div');h.className='ux-scroll-hint';h.textContent='← 表は横にスクロールできます →';w.parentNode.insertBefore(h,w);const refresh=()=>{const needs=w.scrollWidth>w.clientWidth+8;h.classList.toggle('show',needs&&w.scrollLeft<8)};w.addEventListener('scroll',refresh,{passive:true});setTimeout(refresh,0);window.addEventListener('resize',refresh,{passive:true})})}
function cbtControls(){if(page==='q2-cbt.html')return [...document.querySelectorAll('#problem input.answer,#problem select.answer')].filter(x=>!x.disabled&&x.offsetParent!==null);if(page==='q3-cbt.html')return [...document.querySelectorAll('#answerArea input.ans,#answerArea select.ans')].filter(x=>!x.disabled&&x.offsetParent!==null);return[]}
function focusBlank(after){const list=cbtControls();if(!list.length)return;const blank=list.filter(x=>!controlFilled(x));if(!blank.length)return;let target=blank[0];if(after){const i=list.indexOf(after);target=list.slice(i+1).find(x=>!controlFilled(x))||list.slice(0,i+1).find(x=>!controlFilled(x))||blank[0]}target.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});setTimeout(()=>{target.focus({preventScroll:true});if(target.tagName==='INPUT'&&typeof target.select==='function')target.select()},250)}
function updateCbtHelper(){if(!['q2-cbt.html','q3-cbt.html'].includes(page))return;const list=cbtControls(),helper=document.getElementById('uxCbtHelper');if(!helper)return;const done=list.filter(controlFilled).length,total=list.length,all=total>0&&done===total;const b=helper.querySelector('b'),s=helper.querySelector('small'),btn=helper.querySelector('button'),bt=all?'入力完了 ✓':`入力 ${done}/${total}`,st=all?'採点できます。':'空欄を順に埋めればOKです。',tt=all?'入力完了':'次の空欄へ';if(b&&b.textContent!==bt)b.textContent=bt;if(s&&s.textContent!==st)s.textContent=st;if(btn){const dis=all||!total;if(btn.disabled!==dis)btn.disabled=dis;if(btn.textContent!==tt)btn.textContent=tt}}
function setupCbtInputHelper(){if(!['q2-cbt.html','q3-cbt.html'].includes(page))return;const modebar=document.getElementById('modebar');if(modebar&&!document.getElementById('uxCbtHelper')){const h=document.createElement('div');h.id='uxCbtHelper';h.className='ux-cbt-helper';h.innerHTML='<span><b>入力 0/0</b><small>空欄を順に埋めればOKです。</small></span><button type="button">次の空欄へ</button>';modebar.insertAdjacentElement('afterend',h);h.querySelector('button').onclick=()=>focusBlank(document.activeElement)}for(const el of cbtControls()){if(el.dataset.uxInputReady)continue;el.dataset.uxInputReady='1';el.setAttribute('autocomplete','off');if(el.tagName==='INPUT'){el.setAttribute('inputmode','numeric');el.setAttribute('enterkeyhint','next');el.addEventListener('focus',()=>{try{el.select()}catch(e){}});el.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();focusBlank(el)}})}el.addEventListener('focus',()=>{document.querySelectorAll('.ux-focus-row,.ux-focus-box').forEach(x=>x.classList.remove('ux-focus-row','ux-focus-box'));const tr=el.closest('tr'),box=el.closest('.qbox,.card');if(tr)tr.classList.add('ux-focus-row');else if(box)box.classList.add('ux-focus-box')});el.addEventListener('blur',()=>{setTimeout(()=>{document.querySelectorAll('.ux-focus-row,.ux-focus-box').forEach(x=>x.classList.remove('ux-focus-row','ux-focus-box'))},80)})}updateCbtHelper()}
function parseRate(txt){const m=String(txt||'').match(/([\d.]+)\s*\/\s*([\d.]+)/);if(!m)return null;const a=Number(m[1]),b=Number(m[2]);return b>0?a/b:null}
function addReviewLink(host,before,area,label,detail){if(!host||host.querySelector('.ux-next-review'))return;const href=area==='q1'?'q1-cbt.html':area==='q2'?'q2-cbt.html':'q3-cbt.html';const a=document.createElement('a');a.className='ux-next-review';a.href=href;a.innerHTML=`<span class="ux-review-icon">↻</span><span><b>${label}</b><small>${detail}</small></span><span class="ux-review-go">›</span>`;host.insertBefore(a,before||null)}
function enhanceMockResult(){if(page!=='mock.html')return;const host=document.querySelector('#result.show .result-main');if(!host||host.querySelector('.ux-next-review'))return;const parts=[...host.querySelectorAll('.part')].map((el,i)=>({area:['q1','q2','q3'][i],rate:parseRate(el.querySelector('b')?.textContent),name:el.querySelector('span')?.textContent||`第${i+1}問`})).filter(x=>x.rate!=null);if(!parts.length)return;parts.sort((a,b)=>a.rate-b.rate);const w=parts[0];addReviewLink(host,host.querySelector('.result-actions'),w.area,`${w.name}を重点復習する`,'今回もっとも得点率が低かった大問を、本番形式で反復します。')}
function enhanceDailyResult(){if(page!=='daily.html')return;const host=document.querySelector('#quiz .qcard.result');if(!host||host.querySelector('.ux-next-review'))return;const rows=[...host.querySelectorAll('.result-grid > div')].map((el,i)=>({area:['q1','q2','q3'][i],rate:parseRate(el.querySelector('b')?.textContent),name:el.querySelector('span')?.textContent||`第${i+1}問`})).filter(x=>x.rate!=null);if(!rows.length)return;rows.sort((a,b)=>a.rate-b.rate);const w=rows[0],actions=host.querySelector('.actions');addReviewLink(host,actions,w.area,`${w.name}を今すぐ復習する`,'今日の10問で正答率が低かった大問へ、そのまま進みます。');if(actions){const primary=actions.querySelector('.primary');if(primary){primary.classList.remove('primary');primary.classList.add('secondary');primary.textContent='別の10問を作る'}}}
function enhanceResults(){enhanceMockResult();enhanceDailyResult()}
function run(){addStyle();simplifyBeginnerHome();fixQ1RecommendedCount();updateMockProgress();setupMockFinishGuard();enhanceScrollableTables();setupCbtInputHelper();enhanceResults()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
window.addEventListener('pageshow',run);
document.addEventListener('input',()=>{if(page==='mock.html')updateMockProgress();if(['q2-cbt.html','q3-cbt.html'].includes(page))updateCbtHelper()});document.addEventListener('change',()=>{if(page==='mock.html')updateMockProgress();if(['q2-cbt.html','q3-cbt.html'].includes(page))updateCbtHelper()});
const mo=new MutationObserver(()=>{if(page==='mock.html')updateMockProgress();if(['q2-cbt.html','q3-cbt.html','mock.html'].includes(page))enhanceScrollableTables();if(['q2-cbt.html','q3-cbt.html'].includes(page))setupCbtInputHelper();if(page==='q1.html')fixQ1RecommendedCount();enhanceResults()});if(document.documentElement)mo.observe(document.documentElement,{subtree:true,childList:true});
})();